
^https?:\/\/.*\.linkey\.com\/api\/ping\/binary url script-analyze-echo-response https://raw.githubusercontent.com/Keywos/rule/main/script/net_test/js/ntbm.js

^https?:\/\/.*\.linkey\.com\/api\/test url script-echo-response https://raw.githubusercontent.com/Keywos/rule/main/script/net_test/js/nt.js

^https?:\/\/.*\.linkey\.com\/api\/ping\? url script-analyze-echo-response https://raw.githubusercontent.com/Keywos/rule/main/script/api_ping/js/api_ping.js

hostname = *.linkey.com